# ============================================================
# reports.py — Daily and weekly report generation (Modules 10, 11)
# ============================================================
from datetime import datetime, date, timedelta
import json
import os
import csv
import pytz
import config
import telegram_bot as tg
from session import Session, et_now

ET = pytz.timezone("America/New_York")


def generate_daily_report(session: Session):
    """Generate and send end-of-day report via Telegram."""
    now = et_now()
    stats = session.summary_stats()
    trades = session.trades_today

    lines = [
        f"📊 <b>DAILY TRADING REPORT — {now.strftime('%Y-%m-%d')}</b>",
        f"Generated by OpenClaw — Ross Cameron Methodology\n",
        f"<b>SESSION SUMMARY</b>",
        f"Trading window: 9:30am to 11:00am Eastern",
        f"Total signals generated: {len(session.signals_today)}",
        f"Total trades taken: {len(trades)}",
        f"Trades passed on: {len(session.signals_today) - len(trades)}\n",
    ]

    if stats:
        lines += [
            f"<b>RESULTS</b>",
            f"Total P&L: ${stats['total_pnl']:.2f}",
            f"Win rate: {stats['win_rate']}%",
            f"Average R: {stats['avg_r']:.2f}R",
            f"Best trade: {stats['best_trade']['ticker']} ${stats['best_trade']['pnl']:.2f}",
            f"Worst trade: {stats['worst_trade']['ticker']} ${stats['worst_trade']['pnl']:.2f}\n",
        ]
    else:
        lines.append("No trades taken today.\n")

    lines += [
        f"<b>DAILY LOSS TRACKER</b>",
        f"Starting limit: ${session.daily_loss_limit:.2f}",
        f"Loss incurred: ${session.daily_loss_used:.2f}",
        f"Limit hit: {'YES' if session.trading_suspended else 'NO'}",
        f"Budget remaining: ${session.daily_loss_remaining():.2f}\n",
    ]

    if trades:
        lines.append("<b>TRADE BY TRADE</b>")
        for t in trades:
            pnl_str = f"+${t['pnl']:.2f}" if t["pnl"] >= 0 else f"-${abs(t['pnl']):.2f}"
            lines.append(
                f"{t['entry_time']} {t['ticker']} {t['setup_type']} "
                f"${t['entry_price']:.2f}→${t['exit_price']:.2f} "
                f"{pnl_str} {t['r_multiple']}R [{t['exit_reason']}]"
            )
        lines.append("")

    lines += [
        f"<b>ACCOUNT STATUS</b>",
        f"Opening value: ${session.account_value:.2f}",
        f"Closing value: ${session.account_value + (stats.get('total_pnl', 0) if stats else 0):.2f}",
        f"Net change: ${stats.get('total_pnl', 0):.2f}" if stats else "Net change: $0.00",
    ]

    tg.send("\n".join(lines))

    # Save to weekly log
    _save_to_weekly_log(session, stats, now)


def _save_to_weekly_log(session: Session, stats: dict, now: datetime):
    log = {}
    if os.path.exists(config.WEEKLY_LOG_FILE):
        try:
            with open(config.WEEKLY_LOG_FILE) as f:
                log = json.load(f)
        except Exception:
            pass

    log[now.strftime("%Y-%m-%d")] = {
        "trades": len(session.trades_today),
        "pnl": stats.get("total_pnl", 0) if stats else 0,
        "win_rate": stats.get("win_rate", 0) if stats else 0,
        "avg_r": stats.get("avg_r", 0) if stats else 0,
        "limit_hit": session.trading_suspended,
        "account_value": session.account_value,
    }

    with open(config.WEEKLY_LOG_FILE, "w") as f:
        json.dump(log, f, indent=2)


def generate_weekly_report():
    """Generate and send weekly report every Friday at 4pm ET."""
    if not os.path.exists(config.WEEKLY_LOG_FILE):
        tg.send("📅 Weekly report: No trading data recorded this week.")
        return

    with open(config.WEEKLY_LOG_FILE) as f:
        log = json.load(f)

    # Get last 5 trading days
    now = et_now()
    week_data = []
    for i in range(7):
        d = (now - timedelta(days=i)).strftime("%Y-%m-%d")
        if d in log:
            week_data.append((d, log[d]))

    if not week_data:
        tg.send("📅 Weekly report: No trading data this week.")
        return

    total_trades = sum(d["trades"] for _, d in week_data)
    total_pnl = sum(d["pnl"] for _, d in week_data)
    avg_win_rate = sum(d["win_rate"] for _, d in week_data) / len(week_data)
    avg_r = sum(d["avg_r"] for _, d in week_data) / len(week_data)
    days_limit_hit = sum(1 for _, d in week_data if d["limit_hit"])
    best_day = max(week_data, key=lambda x: x[1]["pnl"])
    worst_day = min(week_data, key=lambda x: x[1]["pnl"])

    lines = [
        f"📅 <b>WEEKLY PERFORMANCE REVIEW</b>",
        f"Week ending {now.strftime('%Y-%m-%d')}\n",
        f"Trading days: {len(week_data)}",
        f"Total trades: {total_trades}",
        f"Total P&L: ${total_pnl:.2f}",
        f"Avg win rate: {avg_win_rate:.1f}%",
        f"Avg R multiple: {avg_r:.2f}R",
        f"Best day: {best_day[0]} ${best_day[1]['pnl']:.2f}",
        f"Worst day: {worst_day[0]} ${worst_day[1]['pnl']:.2f}",
        f"Daily limit hit: {days_limit_hit} day(s)\n",
        f"<b>DAY BY DAY</b>",
    ]

    for d, data in sorted(week_data):
        pnl_str = f"+${data['pnl']:.2f}" if data["pnl"] >= 0 else f"-${abs(data['pnl']):.2f}"
        lines.append(
            f"{d}: {data['trades']} trades | {pnl_str} | "
            f"WR {data['win_rate']}% | {data['avg_r']:.2f}R"
            + (" | ⚠️ LIMIT HIT" if data["limit_hit"] else "")
        )

    tg.send("\n".join(lines))
